apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-image-updater-secret
  namespace: argocd
spec:
  encryptedData:
    argocd.token: AgCfpm0TCZakvVvOx88rPeWZcXdlkWAB5OTtGSEQ+Xw2Ha783x20GHSKc6EEJ8fkjsXA77zfY3y/WXtQEOY8upDE4qX0SBqcEl2cLpxLbfLxBkYeYPEFqjjCEVhO8E6N8kTDGCNphVIBIyfbrSEiCcOOoDrc+faMaCM8KelJQOSIVb8Dt3hq7MKi2Uoupb0h6eGBdmCBPgdZfOzPySndU0UV6XV/FwQtmmThoVzT9x5NR1tt7uS1vG/I2pKxSAHS5rgaE9lOqzoVG+w4ZCGD1Oh0eI94ewLozcCEopb9BJgY6VTulsRQxX1XxMRE6n9B5ICUFY49UWsEWSTup8KBMamQnCOP1S8H7DgCVKl/9/IP6ZQ+6uURh6c+DmJA4OMlsZB6SBtMA/bD9ePuH4qe0/YYGUfk8kR+a6ObojwBtnCdVbSLexcCkH9JNGpN5ogU8K2NsSajrTTeQymgB5XG1vmH2gjy+gthtIWljfg9MGIV3c1KYPKIcDhnL2xDDYDDmwdgeuNeSHDN9HKX8QAYYmp9QmSA468KDLz1oRXl31IDiflVG/feqXI6zkm92hn/p006WatUU7HxsBsf2K0I/w6690TVYMwTSnNdyzMYpRRdYfs1Y4DC9gp2ZR4ChpZXVMp+JT7JpIutIUBdVgfeSMZhJrVS2v3VCeVNUSOJQ+i5dVNjUzvVAu/zdDqpEtgMs/Ca7yi3sK1GjyYfrzOWPMkXzO665j2fs64T+thSbH1tPG8c+Q53aMr58fmWljpHAYPST53pEztjiTnN9CclbJpEMdxwkABxnSdCxUabh5eM01veSiHEN+MxH1u6MDhatkVk87UHgTDJTk76VO72bkFJnvBIJ2szsLYM8AalN0pLfupA2mNcm5Zq6wPbIb917mgWqaqtjc3O2exgJbfEzdeHYcSBuRBuO/zjt1+W60GG/WxgyVct0pQXZtXD9VrmVTqg08v7D3cmwR/KxLIKcwjWB6W+UQlLHsJwzsgwn+Y/B/KAI7N/IavCSkh2vKADXlHjpjEzyxzZ
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: argocd-image-updater-secret
      namespace: argocd

