apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  admin.enabled: "false"
  accounts.image-updater: apiKey
  repositories: |
    - url: https://github.com/vrize/vrizead-manifests
  repository.credentials: |
    - url: https://github.com/vrize/vrizead-manifests
      passwordSecret:
        name: argocd-image-updater-github-credential
        key: password
      usernameSecret:
        name: argocd-image-updater-github-credential
        key: username
