apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.1.1/manifests/ha/install.yaml
- https://raw.githubusercontent.com/argoproj-labs/argocd-image-updater/v0.10.2/manifests/install.yaml

namespace: argocd
