apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: adservice
    newName: docker.io/nyuta01/adservice
    # newTag: "v1.1.1-8-gac9004e0"
