apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cd
spec:
  project: default
  source:
    repoURL: git@github.com:nyuta01/argocd-demo.git
    targetRevision: main
    path: manifests/cd
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra
spec:
  project: default
  source:
    repoURL: git@github.com:nyuta01/argocd-demo.git
    targetRevision: main
    path: manifests/infra
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adservice
  annotations:
    argocd-image-updater.argoproj.io/image-list: nyuta01/adservice:^1.0.0
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    repoURL: git@github.com:nyuta01/argocd-demo.git
    targetRevision: main
    path: manifests/adservice
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
