name: release-please
on:
  push:
    branches:
      - main
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: release-please-action
        id: release
        uses: GoogleCloudPlatform/release-please-action@v2
        with:
          release-type: simple
      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.release.outputs.tag_name }}
        if: ${{ steps.release.outputs.release_created }}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        if: ${{ steps.release.outputs.release_created }}
      - uses: yokawasa/action-setup-kube-tools@v0.7.1
        with:
          kustomize-version: "4.1.3"
          skaffold: "1.24.1"
        if: ${{ steps.release.outputs.release_created }}
      - name: Build Production
        run: skaffold build -d ${{ secrets.DOCKER_HUB_USERNAME }}
        if: ${{ steps.release.outputs.release_created }}
